apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd-server
  namespace: argocd
  annotations:
    kubernetes.io/ingress.class: "{{ .Values.nginx.controller.ingressClassResource }}"
    cert-manager.io/issuer: "{{ .Release.Name }}"
spec:
  rules:
  - host: "argo.k8s.dacamposol.com"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: argocd-server
            port:
              number: 80
