apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: internet--allow-to-from-ingress-controller
spec:
  ingress:
  - {}
  podSelector:
    matchLabels:
      app.kubernetes.io/component: controller
      app.kubernetes.io/instance: {{ .Release.Name }}
  policyTypes:
  - Ingress
