apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Release.Name }}
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: dacamposol@gmail.com
    privateKeySecretRef:
      name: {{ .Release.Name }}
    solvers:
    - http01:
        ingress:
          class: {{ .Values.nginx.controller.ingressClassResource.name }}