apiVersion: v2
name: internet-gateway
description: A Helm chart to internet exposure to the cluster resources

type: application

version: 0.1.0

appVersion: "1.3.1"

dependencies:
- name: ingress-nginx
  alias: nginx
  version: 4.2.5
  repository: https://kubernetes.github.io/ingress-nginx
- name: cert-manager
  version: 1.10.0
  repository: https://charts.jetstack.io
  